### PR TITLE
Migrate 6 Jenkins jobs from normal job to pipeline job.

### PR DESCRIPTION
**Pull request by liushilongbuaa**
Commit files are the Jenkins pipeline files.
The links below are the corresponding Jenkins Job.
https://sonic-jenkins.westus2.cloudapp.azure.com/job/common/job/python-swsssdk-build/
https://sonic-jenkins.westus2.cloudapp.azure.com/job/barefoot/job/buildimage-bf-all/
https://sonic-jenkins.westus2.cloudapp.azure.com/job/broadcom/job/buildimage-brcm-201811/
https://sonic-jenkins.westus2.cloudapp.azure.com/job/broadcom/job/buildimage-brcm-201911/
https://sonic-jenkins.westus2.cloudapp.azure.com/job/mellanox/job/buildimage-mlnx-201911-t0/
https://sonic-jenkins.westus2.cloudapp.azure.com/job/mellanox/job/buildimage-mlnx-rpc-all/

### CODE REVIEW

**Review by qiluo-msft — APPROVED** [review]

**Comment by yxieca** [comment]
Some jobs are keeping 30 builds. That will take a lot of storage, do we need to keep so many builds?

**Comment by liushilongbuaa** [comment]
> keeping 30 builds. That will take a lot of storage, do we need to keep so many

I think 5 is enough. The old job is 30. How many builds do you recommend?

**Comment by yxieca** [comment]
> > keeping 30 builds. That will take a lot of storage, do we need to keep so many
> 
> I think 5 is enough. The old job is 30. How many builds do you recommend?

5 sounds good to me :-) Thanks!

**Review by lguohan — APPROVED** [review]

**Comment by yxieca** [comment]
@liushilongbuaa , existing change looks good.? If so, you can add that with another PR>

**Review by yxieca — APPROVED** [review]

**Pull request closed without merging**
