### PR TITLE
Updating build and sim scripts

### PR DESCRIPTION
**Pull request by wichmanndell**
This set of files is used to build and test the software - integrated with docker.

### CODE REVIEW

**Comment by johnarnold** [comment]
Hi, what are these scripts for?  Are they for a different purpose than the ones in https://github.com/Azure/sonic-buildimage ?

**Comment by wichmanndell** [comment]
I didn't see the directory at the time.  Looking at it, the purpose may be similar I guess these are tailored to the existing Dell repos.

We also don't need a new docker image per subsystem - one fits all should be fine.

**Comment by wichmanndell** [comment]
Hi John,

How would you like to proceed here.  Do we review the tools together and them just commit them individually?

**Comment by lguohan** [comment]
not needed since the latest code is already committed

**Pull request closed without merging**
